### ISSUE TITLE
Add Ask Playwright resource

### ISSUE THREAD

**Issue by lucgagan** [nitya/learn-playwright#1]
I read your blog posts when I was getting started with Playwright! So thank you for all the work you do!

In my journey of continuous learning and giving back to the tech community, I've recently developed a tool that I'm quite excited about. I believe it could be of interest to you and your readers. The tool is called Ask Playwright, and it can be found at https://ray.run/ask.

Ask Playwright is leverages the power of a large language model (LLM). It has been trained using the entire [Playwright documentation](https://playwright.dev/). It is designed to answer any queries users might have about Playwright, drawing its responses directly from the most up-to-date information in the documentation.

I believe Ask Playwright can be a fantastic resource for those just starting to learn Playwright, as it provides instant, accurate information drawn directly from a reliable source. It can supplement your already rich content and add a new layer of interaction for your readers, especially for those who are new to Playwright.

I was hoping you might consider sharing Ask Playwright with your audience. I believe it could offer real value and a unique, interactive learning experience for your readers.

Looking forward to hearing your thoughts!

**Comment by nitya** [comment]
@lucgagan - are you part of the Playwright Discord?
https://aka.ms/playwright/discord

They have a section for community folks to share content and resources that could be valuable to the larger community. You should definitely share this there!! I am not actively maintaining this repo (disclosure: I am working on a new series that may replace this) but I will add this to my list of resources to check out as well.

**Comment by lucgagan** [comment]
Thanks!
